#!/bin/bash

echo "🔧 清理Xcode缓存和重新构建"
echo ""

# 清理 DerivedData
echo "1️⃣  清理 DerivedData..."
rm -rf ~/Library/Developer/Xcode/DerivedData/lolo-*
echo "✅ DerivedData 已清理"
echo ""

# 清理项目构建文件
echo "2️⃣  清理项目构建文件..."
cd /Users/lizhicong/Desktop/lolo
rm -rf build/
echo "✅ 构建文件已清理"
echo ""

# 清理 Pods
echo "3️⃣  清理 Pods (可选)..."
echo "如果需要，运行: pod deintegrate && pod install"
echo ""

echo "========================================="
echo "📋 下一步操作："
echo "========================================="
echo ""
echo "1. 在 Xcode 中打开 lolo.xcworkspace"
echo ""
echo "2. 添加新文件到项目（8个文件）："
echo "   方法A - 拖拽："
echo "   - 在Finder中打开 /Users/lizhicong/Desktop/lolo/lolo/"
echo "   - 将新的 .h 和 .m 文件拖到Xcode对应文件夹"
echo "   - 确保勾选 'Add to targets: lolo'"
echo ""
echo "   方法B - 右键添加："
echo "   - 右键点击 Models 文件夹 -> Add Files to lolo"
echo "   - 选择 Report.h 和 Report.m"
echo "   - 对 Utils 和 Views 文件夹重复此操作"
echo ""
echo "3. 构建项目 (⌘+B)"
echo ""
echo "4. 如果仍有 LaunchScreen.storyboard 错误："
echo "   - Product -> Clean Build Folder (⇧⌘K)"
echo "   - 重新构建"
echo ""
echo "========================================="
echo "📝 需要添加的文件列表："
echo "========================================="
echo ""
echo "Models/:"
echo "  - Report.h"
echo "  - Report.m"
echo ""
echo "Utils/:"
echo "  - ReportManager.h"
echo "  - ReportManager.m"
echo ""
echo "Views/Home/:"
echo "  - ReportViewController.h"
echo "  - ReportViewController.m"
echo ""
echo "Views/:"
echo "  - TermsAgreementViewController.h"
echo "  - TermsAgreementViewController.m"
echo ""
echo "========================================="
echo "✅ 准备完成！现在打开 Xcode 添加文件并构建"
echo "========================================="
